env:
  global:
    - ARTIFACTS_AWS_REGION=us-east-1
    - ARTIFACTS_S3_BUCKET=matplotlib-test-results
    - secure: RgJI7BBL8aX5FTOQe7xiXqWHMxWokd6GNUWp1NUV2mRLXPb9dI0RXqZt3UJwKTAzf1z/OtlHDmEkBoTVK81E9iUxK5npwyyjhJ8yTJmwfQtQF2n51Q1Ww9p+XSLORrOzZc7kAo6Kw6FIXN1pfctgYq2bQkrwJPRx/oPR8f6hcbY=
    - secure: E7OCdqhZ+PlwJcn+Hd6ns9TDJgEUXiUNEI0wu7xjxB2vBRRIKtZMbuaZjd+iKDqCKuVOJKu0ClBUYxmgmpLicTwi34CfTUYt6D4uhrU+8hBBOn1iiK51cl/aBvlUUrqaRLVhukNEBGZcyqAjXSA/Qsnp2iELEmAfOUa92ZYo1sk=

before_script:
  - gem install travis-artifacts

language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install:
  - pip install -q --use-mirrors nose python-dateutil numpy pep8 pyparsing pillow
  - sudo apt-get update && sudo apt-get -qq install inkscape libav-tools
  - python setup.py install

script:
  - mkdir ../tmp_test_dir
  - cd ../tmp_test_dir
  # The number of processes is hardcoded, because using too many causes the
  # Travis VM to run out of memory (since so many copies of inkscape and
  # ghostscript are running at the same time).
  - echo Testing using 8 processes
  # Generate the font caches in a single process before starting the
  # multiple processes
  - python -c "from matplotlib import font_manager"
  - python ../matplotlib/tests.py -sv --processes=8 --process-timeout=300

after_failure:
  - tar cjf result_images.tar.bz2 result_images
  - travis-artifacts upload --path result_images.tar.bz2
  - echo "The result images will only be uploaded if they are on the matplotlib/matplotlib repo - this is for security reasons to prevent arbitrary PRs echoing security details."
  - echo https://s3.amazonaws.com/matplotlib-test-results/artifacts/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/result_images.tar.bz2
