env:
  global:
    - ARTIFACTS_AWS_REGION=us-east-1
    - ARTIFACTS_S3_BUCKET=matplotlib-test-results
    - secure: RgJI7BBL8aX5FTOQe7xiXqWHMxWokd6GNUWp1NUV2mRLXPb9dI0RXqZt3UJwKTAzf1z/OtlHDmEkBoTVK81E9iUxK5npwyyjhJ8yTJmwfQtQF2n51Q1Ww9p+XSLORrOzZc7kAo6Kw6FIXN1pfctgYq2bQkrwJPRx/oPR8f6hcbY=
    - secure: E7OCdqhZ+PlwJcn+Hd6ns9TDJgEUXiUNEI0wu7xjxB2vBRRIKtZMbuaZjd+iKDqCKuVOJKu0ClBUYxmgmpLicTwi34CfTUYt6D4uhrU+8hBBOn1iiK51cl/aBvlUUrqaRLVhukNEBGZcyqAjXSA/Qsnp2iELEmAfOUa92ZYo1sk=
    - BUILD_DOCS=false
    - TEST_ARGS=--no-pep8
    - NUMPY=numpy

language: python

matrix:
  include:
    - python: 2.6
      env: NUMPY=numpy==1.6
    - python: 2.7
    - python: 3.3
    - python: 3.4
    - python: 2.7
      env: TEST_ARGS=--pep8
    - python: 2.7
      env: BUILD_DOCS=true

install:
  - pip install -q --use-mirrors nose python-dateutil $NUMPY pep8 pyparsing pillow
  - sudo apt-get update && sudo apt-get -qq install inkscape libav-tools gdb ttf-wqy-zenhei
  # We use --no-install-recommends to avoid pulling in additional large latex docs that we don't need

  # We manually install humor sans using the package from Ubuntu 14.10. Unfortunatly humor sans is not
  # availible in the Ubuntu version used by Travis but we can manually install the deb from a later
  # version since is it basically just a .ttf file
  - |
    if [[ $BUILD_DOCS == true ]]; then
      sudo apt-get install -qq --no-install-recommends dvipng texlive-latex-base texlive-latex-extra texlive-fonts-recommended graphviz
      pip install sphinx numpydoc linkchecker
      wget http://mirrors.kernel.org/ubuntu/pool/universe/f/fonts-humor-sans/fonts-humor-sans_1.0-1_all.deb
      sudo dpkg -i fonts-humor-sans_1.0-1_all.deb
      wget https://googlefontdirectory.googlecode.com/hg/ofl/felipa/Felipa-Regular.ttf
      sudo cp Felipa-Regular.ttf /usr/local/share/fonts/
      fc-cache -f -v
    fi;
  - python setup.py install

script:
  # The number of processes is hardcoded, because using too many causes the
  # Travis VM to run out of memory (since so many copies of inkscape and
  # ghostscript are running at the same time).
  - echo Testing using 8 processes
  # Generate the font caches in a single process before starting the
  # multiple processes
  - gcc --version
  - python -c "from matplotlib import font_manager"
  - if [[ $BUILD_DOCS == false ]]; then export MPL_REPO_DIR=$PWD; fi # pep8-conformance test of the examples
  - if [[ $BUILD_DOCS == false ]]; then mkdir ../tmp_test_dir; fi
  - if [[ $BUILD_DOCS == false ]]; then cd ../tmp_test_dir; fi
  - if [[ $BUILD_DOCS == false ]]; then gdb -return-child-result -batch -ex r -ex bt --args python ../matplotlib/tests.py -sv --processes=8 --process-timeout=300 $TEST_ARGS; fi
  - if [[ $BUILD_DOCS == true ]]; then cd doc; python make.py html --small --warningsaserrors; fi
  # We don't build the LaTeX docs here, so linkchecker will complain
  - if [[ $BUILD_DOCS == true ]]; then touch build/html/Matplotlib.pdf; fi
  - if [[ $BUILD_DOCS == true ]]; then linkchecker build/html/index.html; fi

after_failure:
  - tar cjf result_images.tar.bz2 result_images
  - if [[ $TRAVIS_PULL_REQUEST == false ]]; then gem install travis-artifacts; fi
  - if [[ $TRAVIS_PULL_REQUEST == false ]]; then travis-artifacts upload --path result_images.tar.bz2; fi
  - if [[ $TRAVIS_PULL_REQUEST != false ]]; then echo "The result images will only be uploaded if they are on the matplotlib/matplotlib repo - this is for security reasons to prevent arbitrary PRs echoing security details." else echo https://s3.amazonaws.com/matplotlib-test-results/artifacts/${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/result_images.tar.bz2; fi
