# To set up a development environment using conda run:
#
#   conda env create -f environment.yml
#   conda activate mpl-dev
#   pip install --verbose --no-build-isolation --editable ".[dev]"
#
---
name: mpl-dev
channels:
  - conda-forge
dependencies:
  # runtime dependencies
  - cairocffi
  - c-compiler
  - cxx-compiler
  - contourpy>=1.0.1
  - cycler>=0.10.0
  - fonttools>=4.22.0
  - importlib-resources>=3.2.0
  - kiwisolver>=1.3.1
  - pybind11>=2.13.2
  - meson-python>=0.13.1
  - numpy>=1.25
  - pillow>=9
  - pkg-config
  - pygobject
  - pyparsing>=3
  - pyqt
  - python>=3.11
  - python-dateutil>=2.1
  - setuptools_scm
  - wxpython
  # building documentation
  - colorspacious
  - graphviz
  - ipython
  - ipywidgets
  - numpydoc>=1.0
  - packaging>=20
  - pydata-sphinx-theme=0.16.1  # required by mpl-sphinx-theme=3.10
  - pyyaml
  - sphinx>=3.0.0,!=6.1.2
  - sphinx-copybutton
  - sphinx-gallery>=0.12.0
  - joblib  # needed for sphinx-gallery[parallel]
  - sphinx-design
  - sphinx-tags>=0.4.0
  - pystemmer
  - pikepdf
  - pip
  - pip:
      - mpl-sphinx-theme~=3.10.0
      - sphinxcontrib-svg2pdfconverter>=1.1.0
      - sphinxcontrib-video>=0.2.1
  # testing
  - black<26
  - coverage
  - gtk4
  - ipykernel
  - nbconvert[execute]!=6.0.0,!=6.0.1,!=7.3.0,!=7.3.1
  - nbformat!=5.0.0,!=5.0.1
  - pandas!=0.25.0
  - psutil
  - prek
  - pydocstyle>=5.1.0
  - pytest!=4.6.0,!=5.4.0,!=8.1.0
  - pytest-cov
  - pytest-rerunfailures
  - pytest-timeout
  - pytest-xdist
  - tornado
  - pytz
  - ruff
  - tox
