# Circle CI configuration file
# https://circleci.com/docs/

version: 2.1


###########################################
# Define some common steps as YAML anchors.
#

apt-run:  &apt-install
  name: Install apt packages
  command: |
    sudo apt -qq update
    sudo apt install -y \
      inkscape \
      ffmpeg \
      dvipng \
      lmodern \
      cm-super \
      texlive-latex-base \
      texlive-latex-extra \
      texlive-fonts-recommended \
      texlive-latex-recommended \
      texlive-pictures \
      texlive-xetex \
      graphviz \
      fonts-crosextra-carlito \
      fonts-freefont-otf \
      fonts-humor-sans

fonts-run:  &fonts-install
  name: Install custom fonts
  command: |
    mkdir -p ~/.local/share/fonts
    wget -nc https://github.com/google/fonts/blob/master/ofl/felipa/Felipa-Regular.ttf?raw=true -O ~/.local/share/fonts/Felipa-Regular.ttf || true
    fc-cache -f -v
  save_cache:
    key: fonts-2
    paths:
      - ~/.local/share/fonts/
  restore_cache:
    key: fonts-2

pip-run:  &pip-install
  # Upgrade pip and setuptools and wheel to get as clean an install as possible
  name: Upgrade pip, setuptools, wheel
  command: |
    python -mpip install --upgrade --user pip
    python -mpip install --upgrade --user wheel
    python -mpip install --upgrade --user setuptools

deps-run: &deps-install
  name: Install Python dependencies
  command: |
    python -mpip install --user numpy${NUMPY_VERSION} codecov coverage
    python -mpip install --user -r requirements/doc/doc-requirements.txt

mpl-run: &mpl-install
  name: Install Matplotlib
  command: python -mpip install --user -ve .

doc-run: &doc-build
  name: Build documentation
  command: |
    # Set epoch to date of latest tag.
    export SOURCE_DATE_EPOCH="$(git log -1 --format=%at $(git describe --abbrev=0))"
    make html O=-T
    rm -r build/html/_sources
  working_directory: doc

doc-bundle-run: &doc-bundle
  name: Bundle sphinx-gallery documentation artifacts
  command: tar cf doc/build/sphinx-gallery-files.tar.gz doc/api/_as_gen doc/gallery doc/tutorials
  when: always


##########################################
# Here is where the real jobs are defined.
#

jobs:
  docs-python36:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - run: *apt-install
      - run: *fonts-install
      - run: *pip-install
      - run:
           <<: *deps-install
           environment:
             NUMPY_VERSION: "==1.13.0"
      - run: *mpl-install

      - run: *doc-build

      - run: *doc-bundle
      - store_artifacts:
          path: doc/build/sphinx-gallery-files.tar.gz

      - store_artifacts:
          path: doc/build/html

  docs-python37:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout

      - run: *apt-install
      - run: *fonts-install
      - run: *pip-install

      - run: *deps-install
      - run: *mpl-install

      - run: *doc-build

      - run: *doc-bundle
      - store_artifacts:
          path: doc/build/sphinx-gallery-files.tar.gz

      - store_artifacts:
          path: doc/build/html

  docs-python38:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout

      - run: *apt-install
      - run: *fonts-install
      - run: *pip-install

      - run: *deps-install
      - run: *mpl-install

      - run: *doc-build

      - run: *doc-bundle
      - store_artifacts:
          path: doc/build/sphinx-gallery-files.tar.gz

      - store_artifacts:
          path: doc/build/html

      - add_ssh_keys:
          fingerprints:
            - "78:13:59:08:61:a9:e5:09:af:df:3a:d8:89:c2:84:c0"
      - deploy:
          name: "Deploy new docs"
          command: ./.circleci/deploy-docs.sh

#########################################
# Defining workflows gets us parallelism.
#

workflows:
  version: 2
  build:
    jobs:
      - docs-python36
      - docs-python37
      - docs-python38
