# Reference:
# https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
---
blank_issues_enabled: true  # default
contact_links:
  - name: Question/Support/Other
    url: https://discourse.matplotlib.org
    about: If you have a usage question
  - name: Chat with devs
    url: https://gitter.im/matplotlib/matplotlib
    about: Ask short questions about contributing to Matplotlib
