---
name: Mypy Stubtest
on: [pull_request]

permissions:
  contents: read

jobs:
  mypy-stubtest:
    name: mypy-stubtest
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Python 3
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6.2.0
        with:
          python-version: '3.11'

      - name: Set up reviewdog
        uses: reviewdog/action-setup@d8a7baabd7f3e8544ee4dbde3ee41d0011c3a93f  # v1.5.0

      - name: Install tox
        run: python -m pip install tox

      - name: Run mypy stubtest
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -o pipefail
          tox -e stubtest | \
              sed -e "s!.tox/stubtest/lib/python3.11/site-packages!lib!g" | \
              reviewdog \
                -efm '%Eerror: %m' \
                -efm '%CStub: in file %f:%l' \
                -efm '%CStub: in file %f' \
                -efm '%+CRuntime:%.%#' \
                -efm '%+CMISSING' \
                -efm '%+Cdef %.%#' \
                -efm '%+C<%.%#>' \
                -efm '%Z' \
                -reporter=github-check -tee -name=mypy-stubtest \
                -filter-mode=nofilter
