---
name: PR Greetings

on:
  pull_request_target:
    types: opened
  issues:
    types: opened

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: plbstl/first-contribution@4b2b042fffa26792504a18e49aa9543a87bec077  # v4.1.0
        with:
          labels: first-contribution
          pr-opened-msg: >+
            Thank you for opening your first PR into Matplotlib!


            If you have not heard from us in a week or so, please leave a new
            comment below and that should bring it to our attention.
            Most of our reviewers are volunteers and sometimes things fall
            through the cracks.


            You can also join us [on
            gitter](https://gitter.im/matplotlib/matplotlib) for real-time
            discussion.


            For details on testing, writing docs, and our review process,
            please see [the developer
            guide](https://matplotlib.org/devdocs/devel/index.html).

            **Please let us know  if (and how) you use AI, it will help us give you
            better feedback on your PR.**


            We strive to be a welcoming and open project. Please follow our
            [Code of
            Conduct](https://github.com/matplotlib/matplotlib/blob/main/CODE_OF_CONDUCT.md).
          issue-opened-msg: ""
