---
name: 'Close inactive issues'
on:
  schedule:
    - cron: '30 1 * * 2,4,6'

jobs:
  stale:
    if: github.repository == 'matplotlib/matplotlib'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          operations-per-run: 300
          days-before-stale: -1
          stale-pr-label: "status: inactive"
          days-before-pr-close: -1
          stale-issue-label: "status: inactive"
          close-issue-label: "status: closed as inactive"
          days-before-issue-close: 30
          ascending: true
          exempt-issue-labels: "keep"
          exempt-pr-labels: "keep,status: orphaned PR"
